INSERT INTO Votacion VALUES(1, 'PODEMOS');
INSERT INTO Votacion VALUES(2, 'PSOE');
INSERT INTO Votacion VALUES(3, 'PP');
INSERT INTO Votacion VALUES(4, 'CIUDADANOS');

INSERT INTO Votes VALUES(1, 'SI', 1, 0);
INSERT INTO Votes VALUES(2, 'SI', 1, 0);
INSERT INTO Votes VALUES(3, 'NO', 1, 0);
INSERT INTO Votes VALUES(4, 'SI', 1, 0);

INSERT INTO Votes VALUES(5, 'SI', 2, 0);
INSERT INTO Votes VALUES(6, 'NO', 2, 0);
INSERT INTO Votes VALUES(7, 'NO', 2, 0);

INSERT INTO Votes VALUES(8, 'NO', 3, 0);
INSERT INTO Votes VALUES(9, 'NO', 3, 0);
INSERT INTO Votes VALUES(10, 'SI', 3, 0);

INSERT INTO Votes VALUES(11, 'SI', 4, 0);